language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt

sudo: required
services:
  - docker

addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc

script:
  - make test



